// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'apiKeys.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: webAPIKey,
    appId: '1:646096833745:web:8cb27bc727474f28e8c9f0',
    messagingSenderId: '646096833745',
    projectId: 'vera-life-clinic',
    authDomain: 'vera-life-clinic.firebaseapp.com',
    storageBucket: 'vera-life-clinic.firebasestorage.app',
    measurementId: 'G-MMC6Z6LE1C',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: androidAPIKey,
    appId: '1:646096833745:android:d0d0db009aabbcd9e8c9f0',
    messagingSenderId: '646096833745',
    projectId: 'vera-life-clinic',
    storageBucket: 'vera-life-clinic.firebasestorage.app',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: windowsAPIKey,
    appId: '1:646096833745:web:5d650bef6f7ff02fe8c9f0',
    messagingSenderId: '646096833745',
    projectId: 'vera-life-clinic',
    authDomain: 'vera-life-clinic.firebaseapp.com',
    storageBucket: 'vera-life-clinic.firebasestorage.app',
    measurementId: 'G-5HF21BDL1Z',
  );
}
